version: "3.7"

services:
  shortlink:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: shortlink
    hostname: shortlink
    ports:
      - "80:80"
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@shortlinkdb:3306/shortlink
    networks:
      - bridge
    depends_on:
      - shortlinkDB

  shortlinkDB:
    image: mysql:8.0.22
    container_name: shortlinkdb
    hostname: shortlinkdb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - bridge
    volumes:
      - shortlink:/var/lib/mysql

volumes:
  shortlink:

networks:
  bridge:
